APP:
  # ENVIRONMENT: sim
  ENVIRONMENT: prod
  DEBUG: True
  # Only accept True or False

DB_LOCAL:
    # HOST: 172.17.0.1 # linux
    HOST: 127.0.0.1 # windows
    DATABASE: test_ret
    USER: vmran
    PASSWORD: Vixsdeod3
    PORT: 3306
    ECHO: False

DB_LOCAL_CJ_WINDOWS:
    # HOST: 172.17.0.1 # linux
    HOST: 127.0.0.1 # windows
    DATABASE: mytestdb
    USER: testuser
    PASSWORD: testpassword
    PORT: 33060
    ECHO: False

DB_PROD:
    HOST: 10.120.145.103
    DATABASE: db
    USER: vmran
    PASSWORD: Vixsdeod3
    PORT: 3306
    ECHO: False

EVALUATOR:
    MAX_TILT: 50
    DELTA_TILT: 1
    MAX_DELTA_USER_THRP_DL_PERCENTAJE: 5.0
    MAX_DELTA_TRAFFIC_DL_PERCENTAJE: 10.0
    # MIN_USER_AVG: 80.0 # valor válido
    MIN_USER_AVG: 70.0 # sólo para pruebas
    MAX_USER_AVG: 200.0

TERRAIN:
    KM: 30.0
    D: 40
    N_DISTANCE: 5
    TERRAIN_DELTA: 20
    SAMPLES_PERCENTAGE: 95

KAFKA_CLIENT:
    CLIENT_ID: ret_client
    KAFKA_BROKER_URL:
        sim: localhost:9092
        prod: localhost:9092 # sólo para pruebas
        # prod: 192.168.99.100:9092 # valor válido
    MML_TOPIC:
        sim: test_nbi_mml_simu
        prod: test_nbi_mml_simu # sólo para pruebas
        # prod: mml_topic # valor válido
    RST_TOPIC:
        sim: test_nbi_res_simu
        prod: test_nbi_res_simu # sólo para pruebas
        # prod: rst_topic # valor válido
